### ISSUE TITLE
Jumplist support?

### ISSUE THREAD

**Issue by goodboy** [inside/vim-grep-operator#2]
To start, your plugin is fantastic! Finally a good grep integration that leverages some more intermediate features ;)

I was wondering do you think it's possible to integrate the [jumplist](http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations) like in [YCM](https://github.com/Valloric/YouCompleteMe#goto-commands)? I feel like this would be super useful especially when exploring client code (using an API) and then wanting to jump back to the original source file where the plugin was originally invoked.

Let me know if you think this is worth pursuing; I might be able to pump out a PR!

**Comment by inside** [comment]
Hi, thanks for your encouragement!

These commands are implemented in YCM, does it mean you want to more or less duplicate the code?
Maybe I'm maybe missing your point.

I usually use ctags for code exploration. What will be the benefit of your implementation over ctags?

Best,
Yann

**Comment by goodboy** [comment]
@inside as I understand it, tags are primarily for finding declarations and definitions whereas `vim-grep-operator` is for finding every instance of a particular pattern. I personally use `grep` for exploring code which *uses* (or *consumes*) an API as this often gives me insight how something was designed.

I realize this plugin somewhat duplicates YCM's [`GoToReferences`](https://github.com/Valloric/YouCompleteMe#the-gotoreferences-subcommand) subcommand, but I'm not asking to duplicate anything in YCM. IMO the whole point of a plugin like this is to avoid having to install a compiled tool like YCM that isn't yet widely distributed in standard repos.

I'm also just now realizing the jumplist is working already; so maybe there isn't much to do?

I see the use case being where:
- you've grepped a pattern and quickfix buffer opens
- you select a few different locations of interest subsequently opening buffers
- you wish to go back and forth sequentially between prior selections without having to select them from the qf buffer

This does seems to be working already (I guess I didn't try it thoroughly enough hehe)? 

I guess the only thing that would be extra nice is that when you jumplist to a particular location, if that location is in the grep qf buffer maybe it could be highlighted in some way to immediately indicate which selection you're at?

**Comment by inside** [comment]
Hi tgoodlet!

The jumplist is implemented in the vim core, so yes CTRL-O and CTRL-I work whenever a motion is considered as a jump.

> I guess the only thing that would be extra nice is that when you jumplist to a particular location, if that location is in the grep qf buffer maybe it could be highlighted in some way to immediately indicate which selection you're at?

Highlighting the edit buffer's region where the match occured can be a nice to have. Maybe there's an already existing implementation. I suggest having a look at google first before coding.

**Comment by goodboy** [comment]
@inside I web searched a bit but couldn't find anything specific.

To be honest it's probably a bit tangential to this anyway since my original issue was a built-in feature not working the way I expected.

Thanks for all the guidance :)

**Comment by inside** [comment]
You're welcome!
