### ISSUE TITLE
Provide a :Grep command?

### ISSUE THREAD

**Issue by Asheq** [inside/vim-grep-operator#3]
Sometimes I want to invoke grep without using an operator because the word I want to search for is in my head and not currently under the cursor.

I could use the built-in `:grep` command to type in the search term, but I would miss out on a feature that this plugin offers: automatically setting the search register so the search term is highlighted. I think a command called `:Grep` that works just like the built-in `:grep` but also sets the search register would be great. Would this be easy to add to this plugin?

PS: Using operators to grep seems like the Vim way of grepping; not sure why more people don't do it this way. Great plugin!

**Comment by inside** [comment]
Hi Asheq,

Thanks for your interest in this plugin!

This can be done in the .vimrc. For example:
```
command! -complete=file -nargs=+ G :call <sid>MyGrep(<f-args>)

func! s:MyGrep(word)
  let @/ = a:word
  execute ':Ag! ' . a:word
endfunc
```

would create a `:G` user command, call the `MyGrep` function, set the search register and finally execute the search. Here I use the `:Ag` command from the [ag.vim](https://github.com/rking/ag.vim) plugin, but you can replace it by what your need.

Implement such a feature in the vim-grep-operator is, I think, out of scope: as this plugin provides a grep operator and not a grep command.

Does that make sense to you?

Best,

**Comment by Asheq** [comment]
Thanks for the response! Makes sense. I'll close this now.
