### ISSUE TITLE
Does this work with Neovim?

### ISSUE THREAD

**Issue by devlinzed** [inside/vim-grep-operator#4]
This plugin doesn't do anything for me.  I'm using a binding like this, and I see that it's set correctly when I test `map \`.  But thing `\iw` simply inserts `w`.  Is this because I'm using Neovim?

```
nmap \ <Plug>GrepOperatorOnCurrentDirectory
```

**Comment by inside** [comment]
Hi, the mapping you are using is working for me on vim. I'm not sure if it's due to neovim. What about starting neovim only with this plugin and see if it works not?

**Comment by devlinzed** [comment]
Thanks, the problem was on my end, I just wanted to check.  Great work on the plugin.

**Comment by inside** [comment]
Thanks!

Good to know you got it working :+1:
